### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by moreant** [merrycodes/Android-BoXueGu#4]
这是错别字吗🤣 
https://github.com/merrycodes/Android-BoXueGu/blob/867a1c260898b4a395d619d6af7c03b39212cfc6/app/src/main/res/layout/main_view_exercises.xml#L9

可优化的 ViewHolder
https://github.com/merrycodes/Android-BoXueGu/blob/867a1c260898b4a395d619d6af7c03b39212cfc6/app/src/main/java/com/merrycodes/adapter/ExercisesAdapter.java#L70

顺便试一下在提交的时候close我这个issues
[官方文档](https://help.github.com/cn/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Comment by merrycodes** [comment]
已经完善好

**Comment by moreant** [comment]
可以真的能关哈哈哈
